### ISSUE TITLE
Avoid _include for compatibility with Argo API definitions

### ISSUE THREAD

**Issue by jmandel** [microsoft-healthcare-madison/patient-lists-demo#12]
Current demo makes queries like:

    https://hapi.fhir.org/baseR4//Group?_tag=http%3A%2F%2Fhl7.org%2FConnectathon%7C2020-Sep&_include=Group%3Amember

which is convenient but we don't document `_include` as a required parameter for a server to support. We should fetch info on group members in separate API calls for compatibility.

**Comment by barabo** [comment]
Thanks for the report!

Fixed with this: https://github.com/microsoft-healthcare-madison/patient-lists-demo/commit/6ccadbd4ce22e3127e6a68e11bdae82da071d32c
